spec:
  template:
    spec:
      containers:
        - volumeMounts:
          - name: github-config
            mountPath: "/deployments/data/github"
          - name: che-factory-config
            mountPath: "/deployments/data/che/factories"
          - name: app-config
            mountPath: "/deployments/config"
            readOnly: true
      volumes:
      - name: github-config
        secret:
          secretName: github-config
          items:
          - key: github.user 
            path: user 
          - key: github.token
            path: token
      - name: app-config
        configMap:
          name: che-bootializr
          items:
          - key: application.yaml
            path: application.yaml
      - name: che-factory-config
        configMap:
          name: che-factory-config
          items:
          - key: .factory.json.tpl
            path: .factory.json.tpl
